---
# defaults file for eddi
size: 1
image:
  repository: labsai
  image_name: eddi
  tag: latest

mongodb:
  environment: prod
  storageclass_name: managed-nfs-storage
  storage_size: 20G

mongodb_image:
  name: mongo
  tag: 4.2

# Default when condition is false
# playbook will overwrite this variable
no_mongo_setup_enable: false
