apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: eddis.labs.ai
spec:
  group: labs.ai
  names:
    kind: Eddi
    listKind: EddiList
    plural: eddis
    singular: eddi
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: Eddi is the Schema for the eddi API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: EddiSpec defines the desired state of Eddi
          properties:
            size:
              description: Size is the size of the eddi deployment
              format: int32
              type: integer
            mongodb:
              description: Mongodb defines the properties of the deployed mongodb
              properties:
                environment:
                  description: Environment defines the environment of the database
                  type: string
                storageclass_name:
                  description: Storageclass_name defines the storageclass which will be used
                  type: string
                storage_size:
                  description: Storage_size defines the size of the persistentvolumeclaim
                  type: string
              type: object
          required:
          - size
          type: object
        status:
          description: EddiStatus defines the observed state of Eddi
          type: object
          required:
          - conditions
          properties:
            conditions:
              description: Represents the latest available observations of a deployment's
                current state.
              items:
                description: DeploymentCondition describes the state of a deployment
                  at a certain point.
                properties:
                  lastTransitionTime:
                    description: Last time the condition transitioned from one
                      status to another.
                    format: date-time
                    type: string
                  lastUpdateTime:
                    description: The last time this condition was updated.
                    format: date-time
                    type: string
                  message:
                    description: A human readable message indicating details about
                      the transition.
                    type: string
                  reason:
                    description: The reason for the condition's last transition.
                    type: string
                  status:
                    description: Status of the condition, one of True, False,
                      Unknown.
                    type: string
                  type:
                    description: Type of deployment condition.
                    type: string
                required:
                - status
                - type
                type: object
              type: array
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
